### PR TITLE
`MatchExpression` provided for the MATCH composition

### PR DESCRIPTION
**Pull request by klimov-paul**
| Q             | A
| ------------- | ---
| Is bugfix?    | no
| New feature?  | yes
| Breaks BC?    | no
| Tests pass?   | yes
| Fixed issues  | #53

### CODE REVIEW

**Comment by klimov-paul** [comment]
@softark, could you please handle the recent changes in the docs before I make a '2.0.6' release?

**Comment by softark** [comment]
@klimov-paul With pleasure, yes. Please give me a day or two.

**Comment by klimov-paul** [comment]
Sure. Thanks in advance.

**Comment by softark** [comment]
So, I've made a PR on Japanese translation.
I think the original doc is OK.

**Pull request merged**
