### PR TITLE
Brackets error fix

### PR DESCRIPTION
**Pull request by dlasvazi**

### CODE REVIEW

**Comment by samdark** [comment]
What is it fixing exactly?

**Comment by samdark** [comment]
https://github.com/yiisoft/yii2-sphinx/issues/37

**Comment by samdark** [comment]
https://travis-ci.org/yiisoft/yii2-sphinx/jobs/73158270

**Comment by klimov-paul** [comment]
Fix is invalid, which Travis failing tests confirm.

**Pull request closed without merging**
