### PR TITLE
add commands for create, drop index and add, drop columns

### PR DESCRIPTION
**Pull request by troizet**
| Q             | A
| ------------- | ---
| Is bugfix?    | no
| New feature?  | yes
| Breaks BC?    | yes/no
| Tests pass?   | yes/no
| Fixed issues  | comma-separated list of tickets # fixed by the PR, if any

Added implementation of methods for creating, deleting and updating real-time index schema for Sphinx version 3

### CODE REVIEW

**Comment by samdark** [comment]
Interesting. Do you configure indexes via migrations?

**Comment by troizet** [comment]
Yes, I am using migration.
I set up a custom migration command
```
    'controllerMap' => [
        'migrate-manticore' => [
            'class' => \yii\console\controllers\MigrateController::class,
            'migrationNamespaces' => ['app\manticore_migrations'],
            'migrationTable' => 'manticore_migration',
            'migrationPath' => null,
        ],
    ],
```

In the migration itself I've done the following
```
    public function init()
    {
        $this->db = 'manticore_db';
        parent::init();
    }
```

where 'manticore_db' is the connection to the manticore search via yii\db\Connection
```
return [
    'class' => yii\db\Connection::class,
    'dsn' => 'mysql:host=127.0.0.1;port=9306;',
    'username' => '',
    'password' => ''
];
```
The migration history table is stored in mysql.

**Review by samdark — APPROVED** [review]

**Comment by samdark** [comment]
Would you please add a line for CHANGELOG?

**Comment by troizet** [comment]
Done

**Comment by samdark** [comment]
Thank you!

**Pull request merged**
