### PR TITLE
Use phpunit from vendor

### PR DESCRIPTION
**Pull request by machour**
Also removed hhvm and added PHP 7.3

### CODE REVIEW

**Comment by machour** [comment]
Seems to be affected by https://github.com/yiisoft/yii2-elasticsearch/issues/201

**Comment by samdark** [comment]
@machour it's not reverted in master.

**Comment by machour** [comment]
Sounds like a wise decision @samdark.

Tests for this package will work again once 2.0.16.1 is released

**Comment by samdark** [comment]
Merged. Thanks!

**Comment by machour** [comment]
Builds okay with 2.0.16.1

**Pull request merged**
